# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50a4830a2492dde389ea079e1122b4bae303a71db5e75ea6dd934f975c0a165053ef290f6e80cc13cfd0bdbc8be2951996f02e659f8dfcc1398df28031f2102

test:
  secret_key_base: 473e78b7e595c3a82b0f574894abb7c57114511b959342873b4ba4f940cfc7292bef0f9c4abdf0911d28323824b48218973338cc28ca59940ba8a842bb4a1d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
